#############################################################################
#  CONSUL
#
#  Consul is the service catalog that helps discovery between the components
#  Change "-bootstrap" to "-bootstrap-expect 3", then scale to 3 or more to
#  turn this into an HA Consul raft.
#############################################################################
consul:
  image: autopilotpattern/consul:0.7.2-r0.8
  command: >
    /usr/local/bin/containerpilot
    /bin/consul agent -server
      -config-dir=/etc/consul
      -log-level=err
      -bootstrap-expect 1
      -ui-dir /ui
  restart: always
  mem_limit: 128m
  ports:
    - 8500:8500
  dns:
    - 127.0.0.1

#############################################################################
#  PROMETHEUS
#
#  Prometheus is an open source performance monitoring tool
#  it is included here for demo purposes and is not required
#############################################################################
prometheus:
  image: autopilotpattern/prometheus:1.7.1-r20
  restart: always
  mem_limit: 1g
  ports:
    - 9090:9090
  links:
    - consul:consul
  environment:
    - CONSUL=consul
    - CONSUL_AGENT=1
  dns:
    - 127.0.0.1


#############################################################################
#  FRONTEND
#############################################################################
frontend:
  build: ./
  dockerfile: docker/frontend/Dockerfile
  mem_limit: 512m
  links:
    - consul:consul
  env_file:
    - _env
  environment:
    - CONSUL=consul
    - PORT=443
    - REACT_APP_GQL_HOSTNAME=workshop.host
    - REACT_APP_GQL_PORT=443
    - REACT_APP_GQL_PROTOCOL=https
  ports:
    - "80:80"
    - "443:443"
  dns:
    - 127.0.0.1


#############################################################################
#  BACKEND
#############################################################################
api:
  build: docker/api
  mem_limit: 512m
  links:
    - consul:consul
    - rethinkdb:rethinkdb
  env_file:
    - _env
  environment:
    - CONSUL=consul
    - PORT=3000
    - RETHINK_HOST=rethinkdb
  expose:
    - 3000

# Docker-compose wrapper
# Create _env file from running ./setup.sh
compose-api:
  build: docker/compose-api
  links:
    - consul:consul
  expose:
    - 4242
  env_file:
    - _env
  environment:
    - CONSUL=consul
  restart: always

rethinkdb:
  image: rethinkdb
  restart: always
  mem_limit: 1g
  ports:
    - 8080:8080
  expose:
    - 28015
    - 29015
